# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vMJfnMEXCfxtEO9rKWfXkEhsD7hnsZu2
"""

!pip install streamlit pandas scikit-learn requests

import streamlit as st
import pandas as pd
import requests
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ------------------ PAGE CONFIG ------------------
st.set_page_config(page_title="AnimeFlix 🎌", layout="wide")

# ------------------ STYLING ------------------
st.markdown("""
<style>
body {
    background: linear-gradient(135deg, #141e30, #243b55);
    color: white;
}

.title {
    font-size: 50px;
    text-align: center;
    color: #ff4b4b;
}

.card {
    background: rgba(255,255,255,0.05);
    padding: 15px;
    border-radius: 15px;
    transition: 0.3s;
}

.card:hover {
    transform: scale(1.05);
}
</style>
""", unsafe_allow_html=True)

st.markdown('<div class="title">🎌 Anime Recommendation System</div>', unsafe_allow_html=True)

# ------------------ LOAD DATA ------------------
@st.cache_data
def load_data():
    df = pd.read_csv("/content/anime (1).csv")
    df = df[df['type'] == 'Movie']
    df['genre'] = df['genre'].fillna('')
    df['rating'] = df['rating'].fillna(df['rating'].mean())
    return df

df = load_data()

# ------------------ MODEL ------------------
@st.cache_resource
def compute_similarity(data):
    tfidf = TfidfVectorizer(stop_words='english')
    matrix = tfidf.fit_transform(data['genre'])
    return cosine_similarity(matrix, matrix)

cosine_sim = compute_similarity(df)

indices = pd.Series(df.index, index=df['name']).drop_duplicates()

def recommend(name, n=6):
    if name not in indices:
        return pd.DataFrame()
    idx = indices[name]
    scores = list(enumerate(cosine_sim[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)[1:n+1]
    anime_idx = [i[0] for i in scores]
    return df.iloc[anime_idx]

# ------------------ API ------------------
def fetch_details(name):
    url = f"https://api.jikan.moe/v4/anime?q={name}&limit=1"
    try:
        res = requests.get(url).json()
        if res['data']:
            anime = res['data'][0]
            image = anime['images']['jpg']['image_url']
            trailer = anime['trailer']['url']
            return image, trailer
    except:
        pass
    return None, None

# ------------------ UI ------------------
anime_list = df['name'].sort_values().unique()
selected = st.selectbox("🔍 Select Anime", anime_list)

top_n = st.slider("Number of Recommendations", 3, 10, 6)

if st.button("🚀 Recommend"):

    results = recommend(selected, top_n)

    st.subheader("🎯 Recommended Anime")

    cols = st.columns(3)

    for i, (_, row) in enumerate(results.iterrows()):
        image, trailer = fetch_details(row['name'])

        with cols[i % 3]:
            st.markdown('<div class="card">', unsafe_allow_html=True)

            if image:
                st.image(image)

            st.write(f"**{row['name']}**")
            st.write(f"⭐ {row['rating']}")
            st.write(f"🎭 {row['genre']}")

            if trailer:
                st.video(trailer)
            else:
                yt = f"https://www.youtube.com/results?search_query={row['name']} trailer"
                st.markdown(f"[▶️ Watch Trailer]({yt})")

            st.markdown('</div>', unsafe_allow_html=True)

# ------------------ TRENDING ------------------
st.subheader("🔥 Top Rated")

top = df.sort_values(by='rating', ascending=False).head(6)

cols = st.columns(3)

for i, (_, row) in enumerate(top.iterrows()):
    image, _ = fetch_details(row['name'])

    with cols[i % 3]:
        if image:
            st.image(image)
        st.write(f"**{row['name']}**")
        st.write(f"⭐ {row['rating']}")